import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "@/components/providers";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <nav className="bg-white border-b border-gray-100 py-4">
            <div className="container mx-auto px-4 flex justify-between items-center">
              <Link href="/" className="font-bold text-xl text-blue-600">LeetTracker</Link>
              <div className="flex gap-6 text-sm font-medium text-gray-600">
                <Link href="/dashboard" className="hover:text-blue-600">Dashboard</Link>
                <Link href="/problems" className="hover:text-blue-600">Problems</Link>
              </div>
            </div>
          </nav>
          <main>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
